twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      company_name: "GLG Software"
      jY39s: "https://glg-software.com"
      vhRtR: "GLG Software"
      PUIj5: "V0.2.5"
      application_name: "Employee Management Software"
